import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "@/components/nav/Nav";
import Aside from "@/components/aside/Aside";
import { ThemeProvider, useTheme } from 'next-themes'
import WriteButton from "@/components/WriteButton";
import { DialogBox } from "@/components/shadcn-ui/DialogBox";
import { TodoContextProvider } from "@/components/context/TodoContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Simple todo - manage daily tasks",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <head>
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png"/>
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png"/>
        <link rel="manifest" href="/site.webmanifest"></link>
        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png"/>
      </head>
      <body className={`${inter.className} bg-zinc-200 dark:bg-zinc-800 min-h-screen h-screen flex flex-col`}>
        <TodoContextProvider>
        <ThemeProvider themes={['dark', "light",]} defaultTheme="dark">

        
        <Nav/>
        
        <main className="w-full h-full flex overflow-auto">
          <Aside/>
          <div className="w-full h-full flex-1">
            {children}
          </div>
        </main>
        
        <div className="fixed bottom-4 right-4 z-30 max-[500px]:bottom-[95px]">
          <DialogBox>
             <WriteButton/>
          </DialogBox>
        </div>
        </ThemeProvider>
        </TodoContextProvider>
      </body>
    </html>
  );
}
